# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anthrogo < Formula
  desc "A Go port of Anthropic's Claude Code CLI — TUI + headless + HTTP + web UI"
  homepage "https://github.com/Ricardo-M-L/anthrogo"
  version "0.14.1"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ricardo-M-L/anthrogo/releases/download/v0.14.1/anthrogo_0.14.1_darwin_x86_64.tar.gz"
      sha256 "f3e4cf33a77563515adeb819ed007a4ff1457e13db0e807a1f475126b9c200d5"

      define_method(:install) do
        bin.install "anthrogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ricardo-M-L/anthrogo/releases/download/v0.14.1/anthrogo_0.14.1_darwin_arm64.tar.gz"
      sha256 "775b8922e2f83f0ed2d6890e94d1142ca916080c3ec9534a5cb291d69507a486"

      define_method(:install) do
        bin.install "anthrogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ricardo-M-L/anthrogo/releases/download/v0.14.1/anthrogo_0.14.1_linux_x86_64.tar.gz"
      sha256 "300f4ceae56e0e06d928aa2d560e52d9aa18f30e8c7cedf90d4330d84e03bbee"
      define_method(:install) do
        bin.install "anthrogo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ricardo-M-L/anthrogo/releases/download/v0.14.1/anthrogo_0.14.1_linux_arm64.tar.gz"
      sha256 "02929c3c405b11682e749339da3696f75df862bfbef9ee14f01874d8a91a77e4"
      define_method(:install) do
        bin.install "anthrogo"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anthrogo version")
  end
end
