# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anthrogo < Formula
  desc "A Go port of Anthropic's Claude Code CLI — TUI + headless + HTTP + web UI"
  homepage "https://github.com/Ricardo-M-L/anthrogo"
  version "0.14.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ricardo-M-L/anthrogo/releases/download/v0.14.0/anthrogo_0.14.0_darwin_x86_64.tar.gz"
      sha256 "59f25b8d57478be25fef7d20e29f3a9ab7ba89f169e34cc77640c8191bada071"

      define_method(:install) do
        bin.install "anthrogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ricardo-M-L/anthrogo/releases/download/v0.14.0/anthrogo_0.14.0_darwin_arm64.tar.gz"
      sha256 "02d1e060a0b70e2cee38c819f2a238ff91925279c43f95dac1d17f5b562908ec"

      define_method(:install) do
        bin.install "anthrogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ricardo-M-L/anthrogo/releases/download/v0.14.0/anthrogo_0.14.0_linux_x86_64.tar.gz"
      sha256 "613f2ae9cf6cb817d9e1597737580d4b999078eda48c048a08f2be2787c19fb9"
      define_method(:install) do
        bin.install "anthrogo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ricardo-M-L/anthrogo/releases/download/v0.14.0/anthrogo_0.14.0_linux_arm64.tar.gz"
      sha256 "0d0d2fe5f79398a68dc32ae668b4467f5725565cdcedf29aa17e4485d1313426"
      define_method(:install) do
        bin.install "anthrogo"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anthrogo version")
  end
end
